id = 1
name = "linux-qemu"
vm_type = 1
cpu_num = 1
phys_cpu_sets = [1]
entry_point = 0x8008_0000
kernel_load_addr = 0x8008_0000
dtb_load_addr = 0x8000_0000

# The location of image: "memory" | "fs"
# load from memory
image_location = "memory"
kernel_path = "linux-6.6.62.bin"
dtb_path = "linux-qemu.dtb"

# load from file system
# image_location = "fs"
# kernel_path = "linux-arceos-aarch64.bin"
# dtb_path = "linux-rk3588.dtb"

# ramdisk_path = ""
# ramdisk_load_addr = 0
# disk_path = "disk.img"
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    [0x8000_0000, 0x4000_0000, 0x7, 1], # System RAM 1G MAP_IDENTICAL
]

# Pass-through devices
passthrough_devices = [
    ["intc@8000000", 0x800_0000, 0x800_0000, 0x50_000, 0x1],
    ["pl011@9000000", 0x900_0000, 0x900_0000, 0x1000, 0x1],
    ["pl031@9010000", 0x901_0000, 0x901_0000, 0x1000, 0x1],
    ["pl061@9030000", 0x903_0000, 0x903_0000, 0x1000, 0x1],
    # a003000.virtio_mmio virtio_mmio@a003000 
    # a003200.virtio_mmio virtio_mmio@a003200
    ["virtio_mmio", 0xa00_0000, 0xa00_0000, 0x4000, 0x1],
]

# Emu_devices
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig
emu_devices = []
