# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "starry"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# Guest vm physical cpu sets.
phys_cpu_sets = [1]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x8020_0000
# The location of image: "memory" | "fs".
# Load from file system.
image_location = "fs"
# The file path of the kernel image.
kernel_path = "starry_riscv64.bin"
# The load address of the kernel image.
kernel_load_addr = 0x8020_0000
# The file path of the device tree blob (DTB)
dtb_path = "starry_riscv64.bin"
# The load address of the device tree blob (DTB).
dtb_load_addr = 0x8000_0000

# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    [0x8000_0000, 0x100_0000, 0xf, 0], # Low RAM		16M	0b1111  R|W|EXECUTE|U
]

#
# Device specifications
#
[devices]
# Emu_devices
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig
emu_devices = []

# Pass-through devices
# Name Base-Ipa Base-Pa Length Alloc-Irq
passthrough_devices = [
    [
        "PLIC@c000000",
        0x0c00_0000,
        0x0c00_0000,
        0x21_0000,
        0x1,
    ],
    [
        "UART@10000000",
        0x1000_0000,
        0x1000_0000,
        0x1000,
        0x1,
    ],
]