id = 1
name = "arceos"
vm_type = 1
cpu_num = 2
phys_cpu_sets = [1, 2]
entry_point = 0x8020_0000
kernel_path = "arceos-riscv64-smp.bin"
kernel_load_addr = 0x8020_0000
# Memory regions with format (`base_paddr`, `size`, `flags`).
memory_regions = [
    [0x8000_0000, 0x100_0000, 0xf], # Low RAM		16M	0b1111  R|W|EXECUTE|U
    [0x0c00_0000, 0x21_0000, 0x13], # PLIC  0x21_0000	0b10011 R|W|DEVICE
    [0x1000_0000, 0x1000, 0x13],    # UART	     4K	0b10011 R|W|DEVICE
]

# Emu_devices
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig
emu_devices = [
]
